// ⚠️  AUTO-GENERATED — DO NOT EDIT.
// Source of truth: norbo-api/src/shared/invites-contract/index.ts
// Regenerate with `pnpm sync:contracts` in norbo-api.

/**
 * invites-contract — the shared contract for referrals.
 *
 * Single source of truth, defined once and consumed by BOTH norbo-api and
 * norbo-mobile. Framework-free on purpose: only `zod`. The mobile copy is
 * generated by `scripts/sync-shared-contracts.mjs` (`pnpm sync:contracts` in
 * norbo-api) — never edit it by hand.
 *
 * The design in one line: an invitation is a claim on an EMAIL ADDRESS, with no
 * token and no expiry. Whoever signs up with that address converts it. The link
 * the user shares therefore carries nothing and can be forwarded freely.
 */
import { z } from 'zod';

export const INVITE_STATUSES = ['PENDING', 'ACCEPTED'] as const;
export type InviteStatus = (typeof INVITE_STATUSES)[number];

/** POST /me/invites */
export const sendInviteSchema = z.object({
  email: z.string().trim().email().max(254),
});

export type SendInvitePayload = z.infer<typeof sendInviteSchema>;

export interface InviteView {
  readonly id: string;
  /** Normalised (lowercased) — what the signup match is done against. */
  readonly email: string;
  readonly status: InviteStatus;
  /** ISO timestamp of the signup that converted it, or null. */
  readonly acceptedAt: string | null;
  readonly createdAt: string;
}

export interface InviteSummary {
  readonly invites: readonly InviteView[];
  /** Conversions so far — the value the referral badge is built on. */
  readonly acceptedCount: number;
  /** Invitations left today; the cap exists to stop address farming. */
  readonly remainingToday: number;
}
