/**
 * Badge types — re-exported from the generated shared contract so the rest of
 * the app imports from `@/types/*` (the convention news.types.ts follows) and
 * never reaches into `@/shared` directly.
 *
 * The contract file itself is generated by `pnpm sync:contracts` in norbo-api
 * and must not be edited here.
 */
import type {
  BadgeDetail,
  BadgeRarity,
  BadgeSummary,
  BadgeTierView,
  MarkBadgeSeenPayload,
  MetricUnit,
} from "@/shared/gamification-contract";

export type {
  BadgeDetail,
  BadgeRarity,
  BadgeSummary,
  BadgeTierView,
  MarkBadgeSeenPayload,
  MetricUnit,
};
